server.port=807

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@195.168.9.142:1521:xe
spring.datasource.username=carrot1
spring.datasource.password=carrot1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.dir=C:/kwon/fff
categories=패션;전자;생활;스포츠;가구;반려동물;취미;기타

spring.thymeleaf.cache=false